# Generated by Django 3.0.6 on 2020-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_stripepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
